### ISSUE TITLE
Can you please publish?

### ISSUE THREAD

**Issue by dmvieira** [micahscopes/nbmultitask#1]
Hi, I'm trying to extend your module, but I need it published in pypi

**Comment by psychemedia** [comment]
It'd also be handy to make the repo and example notebook runnable in Binderhub?

**Comment by dmvieira** [comment]
I think it's another issue @psychemedia

**Comment by micahscopes** [comment]
@dmvieira very exciting!  I'm working on publishing it now.  

@psychemedia are you saying that publishing this on pypi would make it easier to install on Binderhub?  I don't know Binderhub.  I'll look into it.

**Comment by psychemedia** [comment]
@micahscopes No idea to be honest (I've never published a package). My thinking was confused! Using binderhub would be more about a config to run a setup script that installs the package and then makes tests/examples available for it. I'm not sure if a good pattern exists for using binderhub in this way yet if indeed it is appropriate to use it that way. (On low bandwidth link atm so can't explore.)

**Comment by psychemedia** [comment]
So for example this repo https://github.com/LokiTechnologies/EqualAreaCartogram defines a package and will also run a notebook in binderhub that tests the package. Though it test from a local import rather than a package install. Binderhub uses jupyter-repo2docker to build emvironment and looks for requirements.txt or apt.txt files. I guess postBuild could be use to install the package.

**Comment by dmvieira** [comment]
It's very simple! http://peterdowns.com/posts/first-time-with-pypi.html

**Comment by dmvieira** [comment]
Updates @micahscopes ? Need help?

**Comment by micahscopes** [comment]
@dmvieira here ya go:
https://pypi.python.org/pypi/nbmultitask/0.1.0

**Comment by dmvieira** [comment]
Great!
